### ISSUE TITLE
alter PackageSchema

### ISSUE THREAD

**Issue by codingjoe** [dropseed/django-importmap#24]
Hi there,

I found the package schema a bit confusing when adding multiple packages.

Currently, I'd have to do something like this:
```toml
[[packages]]
name = "htmx.org"
source = "htmx.org@1.9.8"
[[packages]]
lit = "lit"
source = "lit@3.0.2"
```

Yet, from Pipenv or Poetry I am more used to something like this:

```toml
[[packages]]
htmx.org = "1.9.8"
lit = "3.0.2"
```

Maybe this is worth a consideration. I know it's a backwards incompatible change, but since this package is in its early days, this could be the perfect time to do such alterations.

Cheers!
Joe
